/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.dsystem.view;

import br.com.dsystem.controller.FormaPagtoController;
import br.com.dsystem.controller.PedidoCaixaController;
import br.com.dsystem.model.Cliente;
import br.com.dsystem.model.FormaPagto;
import br.com.dsystem.model.Funcionario;
import br.com.dsystem.model.PedidoCaixa;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class DlgPagamento extends javax.swing.JDialog {

    PedidoCaixaController pcController = new PedidoCaixaController(); 
    FormaPagtoController fpController = new FormaPagtoController();
    private BigDecimal totalAPagr = new BigDecimal("0.00");
    private BigDecimal vlTotalPedido = new BigDecimal("0.00");
    private BigDecimal valorPago = new BigDecimal("0.00");
    private BigDecimal troco = new BigDecimal("0.00");
    private BigDecimal valorDesconto = new BigDecimal("0.00");
    private Cliente cli;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    private String dataDoPedido;
    private Date dtPedido;
    private FormaPagto fPagto;
    private String status;
    private Funcionario func;
    private String obsPedido;
    private String codigoPedido;

    /**
     * Creates new form DljPagamento
     */
    public DlgPagamento(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtDesconto.setText("0,0");
        txtTroco.setText("0,0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblVlPedido = new javax.swing.JLabel();
        lblTipoPagto = new javax.swing.JLabel();
        txtValorPago = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblDesconto = new javax.swing.JLabel();
        txtTotalAPagar = new javax.swing.JTextField();
        txtDesconto = new javax.swing.JTextField();
        txtTroco = new javax.swing.JTextField();
        lblTroco = new javax.swing.JLabel();
        btnFinaliza = new javax.swing.JButton();
        jcbAplicaDesconto = new javax.swing.JCheckBox();
        lblValorPedido = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pagamento");

        lblVlPedido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblVlPedido.setText("TOTAL PEDIDO R$:");

        lblTipoPagto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTipoPagto.setText("PAGTO");

        txtValorPago.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtValorPago.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorPagoFocusLost(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pagamento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTotal.setText("TOTAL A PAGAR R$: ");

        lblDesconto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDesconto.setText("DESCONTO R$: ");
        lblDesconto.setEnabled(false);

        txtTotalAPagar.setEditable(false);
        txtTotalAPagar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTotalAPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalAPagarActionPerformed(evt);
            }
        });

        txtDesconto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescontoFocusLost(evt);
            }
        });

        txtTroco.setEditable(false);
        txtTroco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblTroco.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTroco.setText("TROCO R$: ");

        btnFinaliza.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        btnFinaliza.setText("Finalizar");
        btnFinaliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizaActionPerformed(evt);
            }
        });

        jcbAplicaDesconto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jcbAplicaDesconto.setText("Aplicar Desconto");
        jcbAplicaDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAplicaDescontoActionPerformed(evt);
            }
        });

        lblValorPedido.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblValorPedido.setText("000,00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipoPagto)
                            .addComponent(lblTotal)
                            .addComponent(lblDesconto)
                            .addComponent(lblTroco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblVlPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblValorPedido)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbAplicaDesconto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinaliza, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVlPedido)
                    .addComponent(lblValorPedido))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoPagto)
                    .addComponent(txtValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDesconto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTroco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinaliza)
                    .addComponent(jcbAplicaDesconto))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbAplicaDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAplicaDescontoActionPerformed
        if (jcbAplicaDesconto.isSelected()) {
            lblDesconto.setEnabled(true);
            txtDesconto.setEditable(true);

        } else {
            txtDesconto.setText("0.00");
            lblDesconto.setEnabled(false);
            txtDesconto.setEditable(false);
        }
    }//GEN-LAST:event_jcbAplicaDescontoActionPerformed

    private void txtDescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescontoFocusLost
        txtDesconto.setText(completaCamposValores(txtDesconto.getText()));
        atuaizaPagamento();
    }//GEN-LAST:event_txtDescontoFocusLost

    private void txtValorPagoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorPagoFocusLost
        String preco;
        preco = completaCamposValores(txtValorPago.getText());
        txtValorPago.setText(preco);
        atuaizaPagamento();
    }//GEN-LAST:event_txtValorPagoFocusLost

    private void btnFinalizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizaActionPerformed
        atuaizaPagamento();
        if (this.valorPago.compareTo(totalAPagr) < 0) {
            JOptionPane.showMessageDialog(null, "Pedido não pode ser baixado!", "Pagamento", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                Date baixa = new Date();
                String dtBaixa = sdf.format(baixa);
                pcController.baixaPedido(codigoPedido, new BigDecimal(txtTotalAPagar.getText().replace(",", ".")), new BigDecimal(txtDesconto.getText().replace(",", ".")), dtBaixa);
                 JOptionPane.showMessageDialog(null, "Pedido baixado com Sucesso!", "Pagamento", JOptionPane.INFORMATION_MESSAGE);
                 dispose();
            
            } catch (Exception e) {
                 JOptionPane.showMessageDialog(null, e.getMessage(), "Pagamento", JOptionPane.WARNING_MESSAGE);
            }
           
        }
    }//GEN-LAST:event_btnFinalizaActionPerformed

    private void txtTotalAPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalAPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalAPagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgPagamento dialog = new DlgPagamento(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    //METODOS INICIO
    
    public void recebeBaixa( String id_pedido ){
        codigoPedido = id_pedido;
        PedidoCaixa pedido = pcController.pesquisarIdPedido(id_pedido);
        fPagto = fpController.pesquisaIdFormaPagto(Integer.toString(pedido.getFormaPagtoId()));
        lblTipoPagto.setText(fPagto.getDescricao());
        lblValorPedido.setText(pedido.getTotalPedido().toString().replace(".", ","));  
        this.vlTotalPedido = pedido.getTotalPedido();
        txtDesconto.setText("0,00");
        txtTroco.setText("0,00");
        
        if (fPagto.getDescricao().toUpperCase().equals("DINHEIRO")) {
            txtTotalAPagar.setText(this.vlTotalPedido.toString().replace(".", ","));
        } else {
            txtValorPago.setText(this.vlTotalPedido.toString().replace(".", ","));
            txtTotalAPagar.setText(this.vlTotalPedido.toString().replace(".", ","));
        }
    }

    public void recebePagto(Cliente cliente, String dataPedido, FormaPagto pagto, String status, Funcionario func, String obsPedido, String total) {
        try {
            dtPedido = sdf.parse(dataPedido);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }    
        cli = cliente;
        fPagto = pagto;
        this.status = status;
        this.func = func;
        this.obsPedido = obsPedido;

        lblTipoPagto.setText(pagto.getDescricao());
        lblValorPedido.setText(total);
        txtDesconto.setText("0,00");
        txtTroco.setText("0,00");
        this.vlTotalPedido = new BigDecimal(total.replace(",", "."));

        if (pagto.getDescricao().toUpperCase().equals("DINHEIRO")) {
            txtTotalAPagar.setText(this.vlTotalPedido.toString().replace(".", ","));
        } else {
            txtValorPago.setText(this.vlTotalPedido.toString().replace(".", ","));
            txtTotalAPagar.setText(this.vlTotalPedido.toString().replace(".", ","));
        }

    }

    public void atuaizaPagamento() {
        valorDesconto = new BigDecimal(txtDesconto.getText().replace(",", "."));
        totalAPagr = vlTotalPedido.subtract(valorDesconto);
        txtTotalAPagar.setText(totalAPagr.toString().replace(".", ","));
        valorPago = new BigDecimal(txtValorPago.getText().replace(",", "."));
        if (valorPago.compareTo(totalAPagr) >= 0) {
            troco = valorPago.subtract(totalAPagr);
            txtTroco.setText(troco.toString().replace(".", ","));
        } else {
            txtTroco.setText("0,00");
        }
    }

    private String completaCamposValores(String str) {
        if (!str.contains(",")) {
            return str + ",00";
        } else {
            return str;
        }
    }

    // METODOS TERMINO

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinaliza;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox jcbAplicaDesconto;
    private javax.swing.JLabel lblDesconto;
    private javax.swing.JLabel lblTipoPagto;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JLabel lblValorPedido;
    private javax.swing.JLabel lblVlPedido;
    private javax.swing.JTextField txtDesconto;
    private javax.swing.JTextField txtTotalAPagar;
    private javax.swing.JTextField txtTroco;
    private javax.swing.JTextField txtValorPago;
    // End of variables declaration//GEN-END:variables
}
