/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.dsystem.view;

import br.com.dsystem.model.dao.CategoriaDAO;
import br.com.dsystem.model.dao.ProdutoDAO;
import br.com.dsystem.model.Categoria;
import br.com.dsystem.model.Produto;
import br.com.dsystem.util.CamposNumericos;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author david
 */
public class DlgProdutos extends javax.swing.JDialog {

    /**
     * Creates new form JdlLayoutGrades
     */
    public DlgProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtEstoque.setText("0000");
        txtEstoque.setDocument(new CamposNumericos(4));
        txtCPersonalizado.setDocument(new CamposNumericos(4));
        btnSalvar.setVisible(false);
        btnCancelar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        labellCodigo = new javax.swing.JLabel();
        btnPesquisaCodigo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtPesquisaProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtValor = new javax.swing.JFormattedTextField();
        lbValor = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEstoque = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcbCategoria = new javax.swing.JComboBox();
        jrbCEsqoque = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtCPersonalizado = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(72, 128, 242));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Produtos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Produto", "Valor", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduto);
        if (tblProduto.getColumnModel().getColumnCount() > 0) {
            tblProduto.getColumnModel().getColumn(0).setMinWidth(50);
            tblProduto.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblProduto.getColumnModel().getColumn(0).setMaxWidth(50);
            tblProduto.getColumnModel().getColumn(1).setMinWidth(300);
            tblProduto.getColumnModel().getColumn(1).setPreferredWidth(300);
            tblProduto.getColumnModel().getColumn(1).setMaxWidth(350);
            tblProduto.getColumnModel().getColumn(2).setMinWidth(100);
            tblProduto.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblProduto.getColumnModel().getColumn(2).setMaxWidth(100);
            tblProduto.getColumnModel().getColumn(3).setMinWidth(100);
            tblProduto.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblProduto.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        labellCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labellCodigo.setText("Código:");

        btnPesquisaCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPesquisaCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/busca32.png"))); // NOI18N
        btnPesquisaCodigo.setToolTipText("Pesquisar código");
        btnPesquisaCodigo.setMaximumSize(new java.awt.Dimension(32, 32));
        btnPesquisaCodigo.setMinimumSize(new java.awt.Dimension(32, 32));
        btnPesquisaCodigo.setPreferredSize(new java.awt.Dimension(32, 32));
        btnPesquisaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaCodigoActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/novo.png"))); // NOI18N
        btnNovo.setToolTipText("Novo");
        btnNovo.setMaximumSize(new java.awt.Dimension(39, 39));
        btnNovo.setMinimumSize(new java.awt.Dimension(39, 39));
        btnNovo.setName("Novo"); // NOI18N
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        btnEditar.setToolTipText("Editar");
        btnEditar.setMaximumSize(new java.awt.Dimension(39, 39));
        btnEditar.setMinimumSize(new java.awt.Dimension(39, 39));
        btnEditar.setName("Editar"); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salvar.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.setMaximumSize(new java.awt.Dimension(39, 39));
        btnSalvar.setMinimumSize(new java.awt.Dimension(39, 39));
        btnSalvar.setName("Salvar"); // NOI18N
        btnSalvar.setPreferredSize(new java.awt.Dimension(39, 39));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voltar.png"))); // NOI18N
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(39, 39));
        btnCancelar.setMinimumSize(new java.awt.Dimension(39, 39));
        btnCancelar.setName("Cancelar"); // NOI18N
        btnCancelar.setPreferredSize(new java.awt.Dimension(39, 39));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir.png"))); // NOI18N
        btnExcluir.setToolTipText("Excluir");
        btnExcluir.setMaximumSize(new java.awt.Dimension(39, 39));
        btnExcluir.setMinimumSize(new java.awt.Dimension(39, 39));
        btnExcluir.setName("Excluir"); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        txtPesquisaProduto.setBackground(new java.awt.Color(153, 204, 255));
        txtPesquisaProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Pesquisar");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtValor.setEditable(false);
        txtValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorFocusLost(evt);
            }
        });

        lbValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbValor.setText("Valor R$:");

        txtDescricao.setEditable(false);
        txtDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Descrição:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Estoque:");

        txtEstoque.setEditable(false);
        txtEstoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Categoria:");

        jcbCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcbCategoria.setEnabled(false);
        jcbCategoria.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jcbCategoriaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jrbCEsqoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jrbCEsqoque.setText("Controle de Estoque");
        jrbCEsqoque.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Código Personalizado:");

        txtCPersonalizado.setEditable(false);
        txtCPersonalizado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCPersonalizado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCPersonalizadoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCPersonalizado, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jrbCEsqoque)
                                .addGap(111, 111, 111))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lbValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValor)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome)
                    .addComponent(jLabel6)
                    .addComponent(txtCPersonalizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbValor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbCEsqoque)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(labellCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(jLabel2)
                                .addGap(14, 14, 14)
                                .addComponent(txtPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(137, 137, 137)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addComponent(jSeparator1))))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labellCodigo)
                        .addComponent(jLabel2)
                        .addComponent(txtPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPesquisaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        ProdutoDAO dao = new ProdutoDAO();
        List<Produto> produtos = dao.listaProdutos();
        
        DefaultTableModel tblProdutos = (DefaultTableModel) tblProduto.getModel();
        tblProdutos.setNumRows(0);
        
        for (Produto p : produtos) {
            tblProdutos.addRow(new Object[]{
                p.getId(),
                p.getDescricao(),
                p.getPreco(),
                p.getCategoria().getDescricao()
            });
        }

    }//GEN-LAST:event_formWindowActivated

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (txtCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe um produto para exclusão!");
        } else {
            ProdutoDAO dao = new ProdutoDAO();
            int resp = JOptionPane.showConfirmDialog(null, "Confirma a exclusão do Produto?", "Exlcusão", JOptionPane.YES_NO_OPTION);
            if (resp == JOptionPane.YES_OPTION) {
                Produto p = new Produto();
                p.setId(Integer.parseInt(txtCodigo.getText()));
                dao.excluirProdutos(p);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jcbCategoriaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jcbCategoriaAncestorAdded
        CategoriaDAO dao = new CategoriaDAO();
        List<Categoria> categorias = dao.listaCategoria();
        jcbCategoria.removeAllItems();
        
        for (Categoria cat : categorias) {
            jcbCategoria.addItem(cat);
        }

    }//GEN-LAST:event_jcbCategoriaAncestorAdded

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        limpaCampos();
        habilitaEdicao();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void txtValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorFocusLost
        String preco;
        if (!txtValor.getText().contains(",")) {
            preco = txtValor.getText() + ",00";
        } else {
            preco = txtValor.getText();
        }
        
        txtValor.setText(preco);

    }//GEN-LAST:event_txtValorFocusLost

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Produto prod = new Produto();
        ProdutoDAO dao = new ProdutoDAO();
        prod.setCodigoProduto(Integer.parseInt(txtCPersonalizado.getText()));
        prod.setDescricao(txtDescricao.getText());
        prod.setPreco(new BigDecimal(txtValor.getText().replace(",", ".")));
        prod.setQtdEstoquue(Integer.parseInt(txtEstoque.getText()));
        prod.setCategoria((Categoria) jcbCategoria.getSelectedItem());
        prod.setControlaEstoque(jrbCEsqoque.isSelected());
        
        if (txtCodigo.getText().isEmpty()) {
            if (dao.temProduto(txtDescricao.getText()) == true || dao.temProduto(Integer.parseInt(txtCPersonalizado.getText()))) {
                JOptionPane.showMessageDialog(null, "Produto já cadastrado");
            } else {
                dao.cadastraProduto(prod);
                limpaCampos();
                fechaEdicao();
            }
        } else {
            prod.setId(Integer.parseInt(txtCodigo.getText()));
            dao.editaProduto(prod);
            fechaEdicao();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnPesquisaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaCodigoActionPerformed
        if (txtPesquisaProduto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe um produto");
        } else {
            ProdutoDAO dao = new ProdutoDAO();
            String descricao = "%" + txtPesquisaProduto.getText() + "%";
            
            List<Produto> produtos = dao.pesquisaProduto(descricao);
            
            DefaultTableModel tblProdutos = (DefaultTableModel) tblProduto.getModel();
            tblProdutos.setNumRows(0);
            
            for (Produto p : produtos) {
                tblProdutos.addRow(new Object[]{
                    p.getId(),
                    p.getDescricao(),
                    p.getPreco(),
                    p.getCategoria().getDescricao()
                });
                
            }
        }
    }//GEN-LAST:event_btnPesquisaCodigoActionPerformed

    private void tblProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutoMouseClicked
        if (evt.getClickCount() == 2) {
            ProdutoDAO dao = new ProdutoDAO();
            Produto prod = dao.pesquisaProduto(Integer.parseInt(tblProduto.getValueAt(tblProduto.getSelectedRow(), 0).toString()));
            
            txtCodigo.setText(completaCampos(Integer.toString(prod.getId())));
            txtCPersonalizado.setText(completaCampos(Integer.toString(prod.getCodigoProduto())));
            txtDescricao.setText(prod.getDescricao());
            txtValor.setText(prod.getPreco().toString().replace(".", ","));
            txtEstoque.setText(Integer.toString(prod.getQtdEstoquue()));
            jrbCEsqoque.setSelected(prod.isControlaEstoque());
            jcbCategoria.setSelectedItem(prod.getCategoria().getDescricao());
            
        }

        /*
        ClienteDAO dao = new ClienteDAO();
            Cliente cli = dao.buscaCodigoCliente(Integer.parseInt(tblCliente.getValueAt(tblCliente.getSelectedRow(), 0).toString()));
            codigo = cli.getId();
            dispose();
        
        
        
         */
    }//GEN-LAST:event_tblProdutoMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (txtCodigo.getText().isEmpty()) {
            limpaCampos();
            fechaEdicao();
        } else {
            ProdutoDAO dao = new ProdutoDAO();
            Produto prod = dao.pesquisaProduto(Integer.parseInt(txtCodigo.getText()));
            
            txtCPersonalizado.setText(completaCampos(Integer.toString(prod.getCodigoProduto())));
            txtDescricao.setText(prod.getDescricao());
            txtValor.setText(prod.getPreco().toString().replace(".", ","));
            txtEstoque.setText(Integer.toString(prod.getQtdEstoquue()));
            jrbCEsqoque.setSelected(prod.isControlaEstoque());
            jcbCategoria.setSelectedItem(prod.getCategoria().getDescricao());
            
            fechaEdicao();
            
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (txtCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe um Produto para editar ");
        } else {
            habilitaEdicao();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtCPersonalizadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPersonalizadoFocusLost
        txtCPersonalizado.setText(completaCampos(txtCPersonalizado.getText()));

        /*switch (txtCPersonalizado.getText().length()) {
            case 1 ->                 {
                    String codigo = "000" + txtCPersonalizado.getText();
                    txtCPersonalizado.setText(codigo);
                }
            case 2 ->                 {
                    String codigo = "00" + txtCPersonalizado.getText();
                    txtCPersonalizado.setText(codigo);
                }
            case 3 ->                 {
                    String codigo = "0" + txtCPersonalizado.getText();
                    txtCPersonalizado.setText(codigo);
                }
            default -> {
            }
        }*/
    }//GEN-LAST:event_txtCPersonalizadoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgProdutos dialog = new DlgProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisaCodigo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox jcbCategoria;
    private javax.swing.JRadioButton jrbCEsqoque;
    private javax.swing.JLabel labellCodigo;
    private javax.swing.JLabel lbValor;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTextField txtCPersonalizado;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtPesquisaProduto;
    private javax.swing.JFormattedTextField txtValor;
    // End of variables declaration//GEN-END:variables

    //MÉTODOS 
    private void limpaCampos() {
        txtCPersonalizado.setText("");
        txtDescricao.setText("");
        txtValor.setText("");
        txtEstoque.setText("");
        jrbCEsqoque.setSelected(false);
    }
    
    private void habilitaEdicao() {
        txtCPersonalizado.setEditable(true);
        txtDescricao.setEditable(true);
        jcbCategoria.setEnabled(true);
        txtValor.setEditable(true);
        txtEstoque.setEditable(true);
        jrbCEsqoque.setEnabled(true);
        btnNovo.setVisible(false);
        btnEditar.setVisible(false);
        btnExcluir.setVisible(false);
        btnSalvar.setVisible(true);
        btnCancelar.setVisible(true);
        
    }
    
    private void fechaEdicao() {
        txtCPersonalizado.setEditable(false);
        txtDescricao.setEditable(false);
        jcbCategoria.setEnabled(false);
        txtValor.setEditable(false);
        txtEstoque.setEditable(false);
        jrbCEsqoque.setEnabled(false);
        btnNovo.setVisible(true);
        btnEditar.setVisible(true);
        btnExcluir.setVisible(true);
        btnSalvar.setVisible(false);
        btnCancelar.setVisible(false);
    }
    
    private String completaCampos(String str){
        switch (str.length()) {
            case 1 -> {
                return "000" + str;
            }
            case 2 -> {
                return "00" + str;
            }
            case 3 -> {
                return "0" + str;
            }
            default -> {
                return str;
            }
        }
    }
    
}
