/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.dsystem.view;

import br.com.dsystem.controller.BordaController;
import br.com.dsystem.controller.CategoriaController;
import br.com.dsystem.controller.ClienteController;
import br.com.dsystem.controller.FormaPagtoController;
import br.com.dsystem.controller.ProdutoControl;
import br.com.dsystem.model.dao.ClienteDAO;
import br.com.dsystem.model.Borda;
import br.com.dsystem.model.CarrinhoPedido;
import br.com.dsystem.model.Categoria;
import br.com.dsystem.model.Cliente;
import br.com.dsystem.model.FormaPagto;
import br.com.dsystem.model.Funcionario;
import br.com.dsystem.model.Produto;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author david
 */
public class DlgPedidoCaixaTeste extends javax.swing.JDialog {

    private BigDecimal total = new BigDecimal(0.0);
    private BigDecimal preco = new BigDecimal(0.0);
    private BigDecimal subtotal = new BigDecimal(0.0);
    private int qtd = 0;
    private int x = 0;
    private String descProd;

    private final ClienteController cliController = new ClienteController();
    FormaPagtoController controlFPagto = new FormaPagtoController();
    Funcionario func = new Funcionario();

    public String getDescProd() {
        return descProd;
    }

    DefaultTableModel carrinho;

    /**
     * Creates new form DlgLayoutPedido
     */
    public DlgPedidoCaixaTeste(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregaData();
        carregaJcbCategoria();
        carregaJcbFPagto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelPedido = new javax.swing.JPanel();
        panelDadosPedido = new javax.swing.JPanel();
        btnAdicionaProduto = new javax.swing.JButton();
        btnRemoveProduto = new javax.swing.JButton();
        jcbFormaPagto = new javax.swing.JComboBox();
        lblFormaPagto = new javax.swing.JLabel();
        panelBorda = new javax.swing.JPanel();
        jcbBorda = new javax.swing.JComboBox<>();
        txtValorBorda = new javax.swing.JTextField();
        panelSabores = new javax.swing.JPanel();
        btnAddSabor = new javax.swing.JButton();
        panelIngredientes = new javax.swing.JPanel();
        btnAddIngr = new javax.swing.JButton();
        btnRemoveIngr = new javax.swing.JButton();
        lblObsPedido = new javax.swing.JLabel();
        txtObsPedido = new javax.swing.JTextField();
        lblProduto = new javax.swing.JLabel();
        jcbProduto = new javax.swing.JComboBox<>();
        txtQtdProduto = new javax.swing.JTextField();
        lblQtdProduto = new javax.swing.JLabel();
        txtValorProduto = new javax.swing.JTextField();
        lblValorProduto = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        jcbCategoria = new javax.swing.JComboBox();
        lblCodProduto = new javax.swing.JLabel();
        txtCodProduto = new javax.swing.JTextField();
        btnBuscaProdCod = new javax.swing.JButton();
        panelDadosCliente = new javax.swing.JPanel();
        btnBuscaCelular = new javax.swing.JButton();
        btnBuscaNomeCli = new javax.swing.JButton();
        lblCelular = new javax.swing.JLabel();
        txtCelular = new javax.swing.JFormattedTextField();
        txtData = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblCompl = new javax.swing.JLabel();
        txtCompl = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblCEP = new javax.swing.JLabel();
        txtCEP = new javax.swing.JFormattedTextField();
        lblObsCliente = new javax.swing.JLabel();
        txtObsCliente = new javax.swing.JTextField();
        panelCarrinho = new javax.swing.JPanel();
        btnPagamento = new javax.swing.JButton();
        btnCancelaPedido = new javax.swing.JButton();
        btnImprimePedido = new javax.swing.JButton();
        panelTotalPedido = new javax.swing.JPanel();
        txtTotalPedido = new javax.swing.JTextField();
        lblTotalPedido = new javax.swing.JLabel();
        lblStatusPedido = new javax.swing.JLabel();
        jcbStatus = new javax.swing.JComboBox<>();
        lblAtendente = new javax.swing.JLabel();
        txtAtendente = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCarrinho = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pedido Caixa");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panelTitulo.setBackground(new java.awt.Color(0, 0, 255));
        panelTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 32)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Pedido Caixa");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelPedido.setBackground(new java.awt.Color(255, 255, 255));

        panelDadosPedido.setBackground(new java.awt.Color(255, 255, 255));
        panelDadosPedido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        btnAdicionaProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdicionaProduto.setText("Adicionar Produto");
        btnAdicionaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionaProdutoActionPerformed(evt);
            }
        });

        btnRemoveProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRemoveProduto.setText("Remover produto");

        jcbFormaPagto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblFormaPagto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFormaPagto.setText("Forma de Pagamento:");

        panelBorda.setBackground(new java.awt.Color(255, 255, 255));
        panelBorda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Borda", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BELOW_TOP));

        jcbBorda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcbBorda.setEnabled(false);
        jcbBorda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbBordaItemStateChanged(evt);
            }
        });

        txtValorBorda.setEditable(false);
        txtValorBorda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout panelBordaLayout = new javax.swing.GroupLayout(panelBorda);
        panelBorda.setLayout(panelBordaLayout);
        panelBordaLayout.setHorizontalGroup(
            panelBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBordaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbBorda, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtValorBorda, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBordaLayout.setVerticalGroup(
            panelBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jcbBorda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtValorBorda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelSabores.setBackground(new java.awt.Color(255, 255, 255));
        panelSabores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sabores", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BELOW_TOP));

        btnAddSabor.setText("Adicionar");
        btnAddSabor.setEnabled(false);

        javax.swing.GroupLayout panelSaboresLayout = new javax.swing.GroupLayout(panelSabores);
        panelSabores.setLayout(panelSaboresLayout);
        panelSaboresLayout.setHorizontalGroup(
            panelSaboresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSaboresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddSabor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSaboresLayout.setVerticalGroup(
            panelSaboresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAddSabor)
        );

        panelIngredientes.setBackground(new java.awt.Color(255, 255, 255));
        panelIngredientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingredientes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BELOW_TOP));

        btnAddIngr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddIngr.setText("Adicionar");
        btnAddIngr.setEnabled(false);

        btnRemoveIngr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRemoveIngr.setText("Remover");
        btnRemoveIngr.setEnabled(false);

        javax.swing.GroupLayout panelIngredientesLayout = new javax.swing.GroupLayout(panelIngredientes);
        panelIngredientes.setLayout(panelIngredientesLayout);
        panelIngredientesLayout.setHorizontalGroup(
            panelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngredientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddIngr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemoveIngr))
        );
        panelIngredientesLayout.setVerticalGroup(
            panelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnAddIngr)
                .addComponent(btnRemoveIngr))
        );

        lblObsPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblObsPedido.setText("Obs Pedido:");

        txtObsPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblProduto.setText("Produto:");

        jcbProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcbProduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbProdutoItemStateChanged(evt);
            }
        });

        txtQtdProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblQtdProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQtdProduto.setText("Qtd.:");

        txtValorProduto.setEditable(false);
        txtValorProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblValorProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblValorProduto.setText("Valor:");

        lblCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCategoria.setText("Categoria");

        jcbCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcbCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbCategoriaItemStateChanged(evt);
            }
        });

        lblCodProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCodProduto.setText("Código Produto:");

        txtCodProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnBuscaProdCod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/busca32.png"))); // NOI18N
        btnBuscaProdCod.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelDadosPedidoLayout = new javax.swing.GroupLayout(panelDadosPedido);
        panelDadosPedido.setLayout(panelDadosPedidoLayout);
        panelDadosPedidoLayout.setHorizontalGroup(
            panelDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosPedidoLayout.createSequentialGroup()
                .addGroup(panelDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosPedidoLayout.createSequentialGroup()
                        .addGroup(panelDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDadosPedidoLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(btnAdicionaProduto)
                                .addGap(146, 146, 146)
                                .addComponent(btnRemoveProduto))
                            .addGroup(panelDadosPedidoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblFormaPagto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbFormaPagto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelDadosPedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDadosPedidoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(panelBorda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panelSabores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDadosPedidoLayout.createSequentialGroup()
                                .addComponent(lblObsPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtObsPedido))
                            .addGroup(panelDadosPedidoLayout.createSequentialGroup()
                                .addComponent(lblProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValorProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblQtdProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDadosPedidoLayout.createSequentialGroup()
                                .addComponent(lblCategoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCodProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscaProdCod, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panelDadosPedidoLayout.setVerticalGroup(
            panelDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDadosPedidoLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(panelDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCategoria)
                        .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCodProduto)
                        .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscaProdCod, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtQtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblQtdProduto)
                        .addComponent(txtValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblValorProduto))
                    .addComponent(lblProduto, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblObsPedido)
                    .addComponent(txtObsPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBorda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSabores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbFormaPagto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFormaPagto))
                .addGap(16, 16, 16)
                .addGroup(panelDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionaProduto)
                    .addComponent(btnRemoveProduto))
                .addContainerGap())
        );

        panelDadosCliente.setBackground(new java.awt.Color(255, 255, 255));
        panelDadosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Cliente"));

        btnBuscaCelular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/busca32.png"))); // NOI18N
        btnBuscaCelular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscaCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaCelularActionPerformed(evt);
            }
        });

        btnBuscaNomeCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/busca32.png"))); // NOI18N
        btnBuscaNomeCli.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblCelular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCelular.setText("Celular:");

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtData.setEditable(false);
        txtData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblData.setText("Data:");

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Nome:");

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEndereco.setText("End.:");

        txtEndereco.setEditable(false);
        txtEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNumero.setText("Nº.:");

        txtNumero.setEditable(false);
        txtNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblCompl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCompl.setText("Compl.:");

        txtCompl.setEditable(false);
        txtCompl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBairro.setText("Bairro:");

        txtBairro.setEditable(false);
        txtBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCidade.setText("Cidade:");

        txtCidade.setEditable(false);
        txtCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblCEP.setText("CEP:");

        txtCEP.setEditable(false);
        try {
            txtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCEP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblObsCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblObsCliente.setText("Obs:");

        txtObsCliente.setEditable(false);
        txtObsCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout panelDadosClienteLayout = new javax.swing.GroupLayout(panelDadosCliente);
        panelDadosCliente.setLayout(panelDadosClienteLayout);
        panelDadosClienteLayout.setHorizontalGroup(
            panelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosClienteLayout.createSequentialGroup()
                        .addGroup(panelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCelular)
                            .addComponent(lblNome)
                            .addComponent(lblEndereco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelDadosClienteLayout.createSequentialGroup()
                                .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscaCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDadosClienteLayout.createSequentialGroup()
                                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNumero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCompl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCompl))
                            .addGroup(panelDadosClienteLayout.createSequentialGroup()
                                .addComponent(txtNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscaNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelDadosClienteLayout.createSequentialGroup()
                        .addGroup(panelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBairro)
                            .addComponent(lblObsCliente))
                        .addGap(18, 18, 18)
                        .addGroup(panelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDadosClienteLayout.createSequentialGroup()
                                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCEP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtObsCliente))))
                .addContainerGap())
        );
        panelDadosClienteLayout.setVerticalGroup(
            panelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCelular)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscaCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblData)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscaNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNome)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCompl)
                    .addComponent(txtCompl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCidade)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCEP)
                    .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblObsCliente)
                    .addComponent(txtObsCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPedidoLayout = new javax.swing.GroupLayout(panelPedido);
        panelPedido.setLayout(panelPedidoLayout);
        panelPedidoLayout.setHorizontalGroup(
            panelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDadosPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDadosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPedidoLayout.setVerticalGroup(
            panelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDadosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDadosPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelCarrinho.setBackground(new java.awt.Color(255, 255, 255));

        btnPagamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPagamento.setText("Pagamento");
        btnPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagamentoActionPerformed(evt);
            }
        });

        btnCancelaPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelaPedido.setText("Cancelar");

        btnImprimePedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnImprimePedido.setText("Imprimir Pedido");

        panelTotalPedido.setBackground(new java.awt.Color(102, 102, 102));

        txtTotalPedido.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txtTotalPedido.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblTotalPedido.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        lblTotalPedido.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalPedido.setText("TOTAL PEDIDO R$:");

        javax.swing.GroupLayout panelTotalPedidoLayout = new javax.swing.GroupLayout(panelTotalPedido);
        panelTotalPedido.setLayout(panelTotalPedidoLayout);
        panelTotalPedidoLayout.setHorizontalGroup(
            panelTotalPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTotalPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotalPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(txtTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTotalPedidoLayout.setVerticalGroup(
            panelTotalPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTotalPedidoLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(panelTotalPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalPedido))
                .addGap(17, 17, 17))
        );

        lblStatusPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStatusPedido.setText("Status:");

        jcbStatus.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INICIADO", "EM PREPARAÇÃO", "PRONTO", "SAIU PARA ENTREGA", "ENTREGUE" }));
        jcbStatus.setEnabled(false);

        lblAtendente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAtendente.setText("Atendente:");

        txtAtendente.setEditable(false);
        txtAtendente.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAtendenteActionPerformed(evt);
            }
        });

        txtCarrinho.setEditable(false);
        txtCarrinho.setColumns(20);
        txtCarrinho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCarrinho.setRows(10);
        jScrollPane2.setViewportView(txtCarrinho);

        javax.swing.GroupLayout panelCarrinhoLayout = new javax.swing.GroupLayout(panelCarrinho);
        panelCarrinho.setLayout(panelCarrinhoLayout);
        panelCarrinhoLayout.setHorizontalGroup(
            panelCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCarrinhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelTotalPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCarrinhoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnImprimePedido)
                        .addGap(39, 39, 39)
                        .addComponent(btnCancelaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCarrinhoLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblStatusPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAtendente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAtendente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelCarrinhoLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        panelCarrinhoLayout.setVerticalGroup(
            panelCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCarrinhoLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatusPedido)
                    .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAtendente)
                    .addComponent(txtAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPagamento)
                    .addComponent(btnImprimePedido)
                    .addComponent(btnCancelaPedido))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelCarrinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCarrinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAtendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAtendenteActionPerformed

    private void jcbCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbCategoriaItemStateChanged
        Categoria cat = (Categoria) jcbCategoria.getSelectedItem();
        carregaJcbProduto(cat);

        if (cat.isTemBorda() == true) {
            jcbBorda.setEnabled(true);
            carregaJcbBorda();
            Borda borda = (Borda) jcbBorda.getSelectedItem();
            txtValorBorda.setText(borda.getValor().toString().replace(".", ","));
        } else {
            txtValorBorda.setText("");
            jcbBorda.setEnabled(false);
        }

        if (cat.isVariosSabores() == true) {
            btnAddIngr.setEnabled(true);
            btnRemoveIngr.setEnabled(true);
            btnAddSabor.setEnabled(true);

        } else {
            btnAddIngr.setEnabled(false);
            btnRemoveIngr.setEnabled(false);
            btnAddSabor.setEnabled(false);
        }

        Produto prod = (Produto) jcbProduto.getSelectedItem();
        descProd = prod.getDescricao();
        txtCodProduto.setText(Integer.toString(prod.getCodigoProduto()));
        txtValorProduto.setText(prod.getPreco().toString().replace(".", ","));
    }//GEN-LAST:event_jcbCategoriaItemStateChanged

    private void jcbBordaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbBordaItemStateChanged
        Borda borda = (Borda) jcbBorda.getSelectedItem();
        txtValorBorda.setText(borda.getValor().toString().replace(".", ","));
    }//GEN-LAST:event_jcbBordaItemStateChanged

    private void jcbProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbProdutoItemStateChanged
        Produto prod = (Produto) jcbProduto.getSelectedItem();
        txtValorProduto.setText(prod.getPreco().toString().replace(".", ","));
    }//GEN-LAST:event_jcbProdutoItemStateChanged

    private void btnBuscaCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaCelularActionPerformed
        if (txtCelular.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe um Celular para pesquisa", "Busca Cliente", JOptionPane.INFORMATION_MESSAGE);
        } else {
            ClienteDAO dao = new ClienteDAO();

            if (cliController.validaCelularCli(txtCelular.getText())) {
                Cliente cli = cliController.pesquisaCliCelular(txtCelular.getText());
                txtNome.setText(cli.getNome());
                txtEndereco.setText(cli.getEndereco());
                txtNumero.setText(Integer.toString(cli.getNumero()));
                txtCompl.setText(cli.getCompl());
                txtBairro.setText(cli.getBairro());
                txtCidade.setText(cli.getCidade());
                txtCEP.setText(cli.getCep());
                txtObsCliente.setText(cli.getObs());
            } else {

                DlgAdicionaCliente adicionaCliente = new DlgAdicionaCliente(new javax.swing.JDialog(), true);

                adicionaCliente.recebeForne(txtCelular.getText());

                adicionaCliente.setVisible(true);

                Cliente cli = cliController.pesquisaCliCelular(txtCelular.getText());
                txtNome.setText(cli.getNome());
                txtEndereco.setText(cli.getEndereco());
                txtNumero.setText(Integer.toString(cli.getNumero()));
                txtCompl.setText(cli.getCompl());
                txtBairro.setText(cli.getBairro());
                txtCidade.setText(cli.getCidade());
                txtCEP.setText(cli.getCep());
                txtObsCliente.setText(cli.getObs());
            }

        }
    }//GEN-LAST:event_btnBuscaCelularActionPerformed

    private void btnAdicionaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionaProdutoActionPerformed

        if (Integer.parseInt(txtQtdProduto.getText()) < 1 || txtQtdProduto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Quantidade inválida!\nO Produto deve ter pelo menos 1 quantidade.", "Pedido Caixa", JOptionPane.ERROR_MESSAGE);

        } else {
            qtd = Integer.parseInt(txtQtdProduto.getText());
            BigDecimal qntd = new BigDecimal(qtd);
            preco = new BigDecimal(txtValorProduto.getText().replace(",", "."));

            subtotal = preco.multiply(qntd);

            total = total.add(subtotal);

            CarrinhoPedido c = new CarrinhoPedido();

            Produto p = (Produto) jcbProduto.getSelectedItem();
            c.setProduto(p);
            c.setQuantidade(qtd);
            c.setSubtotal(subtotal);
            
            x++;
            if (x==1){
                cabecalhoCarrinho();
            }
            txtCarrinho.setText(txtCarrinho.getText()+"\n"+Integer.toString(c.getQuantidade())+"\t"+Integer.toString(c.getProduto().getCodigoProduto())+"\t"+c.getProduto().getDescricao()+"\t\t"+c.getProduto().getPreco()+"\t"+subtotal);
            
           

            txtTotalPedido.setText(total.toString().replace(".", ","));

        }

    }//GEN-LAST:event_btnAdicionaProdutoActionPerformed

    private void btnPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagamentoActionPerformed
        DlgPagamento dialogPgto = new DlgPagamento(new javax.swing.JDialog(), true);
        Cliente cliente = cliController.pesquisaCliCelular(txtCelular.getText());
        String dataPedido = txtData.getText();
        FormaPagto pagto = controlFPagto.pesquisaDescFPagto(jcbFormaPagto.getSelectedItem().toString()); 
        String obsPedido = txtObsPedido.getText();
        
        dialogPgto.recebePagto(cliente, dataPedido, pagto,jcbStatus.getSelectedItem().toString(), func, obsPedido, txtTotalPedido.getText());
        dialogPgto.setVisible(true);

    }//GEN-LAST:event_btnPagamentoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         txtAtendente.setText(func.getNome());
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgPedidoCaixaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgPedidoCaixaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgPedidoCaixaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgPedidoCaixaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgPedidoCaixaTeste dialog = new DlgPedidoCaixaTeste(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    //INICIOS MÉTODDOS
     public void rebeceAtendente(Funcionario f) {
        this.func = f;
    }

    public Funcionario carregaAtendente() {
        return this.func;
    }
    
    private void carregaData() {
        Date hoje = new Date();
        SimpleDateFormat dataBr = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        String dataFormatada = dataBr.format(hoje);

        txtData.setText(dataFormatada);
    }

    private void carregaJcbFPagto() {
        jcbFormaPagto.setModel(controlFPagto.listarComboFPagto());
    }

    private void carregaJcbCategoria() {

        CategoriaController controlCat = new CategoriaController();
        jcbCategoria.setModel(controlCat.listarComboCategoria());
    }

    private void carregaJcbProduto(Categoria c) {

        ProdutoControl controlProd = new ProdutoControl();
        jcbProduto.setModel(controlProd.listarProdutos(c));
    }

    private void carregaJcbBorda() {

        BordaController controlBorda = new BordaController();
        jcbBorda.setModel(controlBorda.listarComboBorda());
    }

    private void cabecalhoCarrinho() {
        txtCarrinho.setText("*******************************************************************************\n"
                            +"                                            PEDIDO CAIXA                      \n"
                            +"*******************************************************************************\n"
                            +"Qtd   Código   Produto\t\t\tValor  Subtotal");
    }

    // FIM MÉTODOS

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddIngr;
    private javax.swing.JButton btnAddSabor;
    private javax.swing.JButton btnAdicionaProduto;
    private javax.swing.JButton btnBuscaCelular;
    private javax.swing.JButton btnBuscaNomeCli;
    private javax.swing.JButton btnBuscaProdCod;
    private javax.swing.JButton btnCancelaPedido;
    private javax.swing.JButton btnImprimePedido;
    private javax.swing.JButton btnPagamento;
    private javax.swing.JButton btnRemoveIngr;
    private javax.swing.JButton btnRemoveProduto;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcbBorda;
    private javax.swing.JComboBox jcbCategoria;
    private javax.swing.JComboBox jcbFormaPagto;
    private javax.swing.JComboBox<String> jcbProduto;
    private javax.swing.JComboBox<String> jcbStatus;
    private javax.swing.JLabel lblAtendente;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCodProduto;
    private javax.swing.JLabel lblCompl;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblFormaPagto;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblObsCliente;
    private javax.swing.JLabel lblObsPedido;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblQtdProduto;
    private javax.swing.JLabel lblStatusPedido;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalPedido;
    private javax.swing.JLabel lblValorProduto;
    private javax.swing.JPanel panelBorda;
    private javax.swing.JPanel panelCarrinho;
    private javax.swing.JPanel panelDadosCliente;
    private javax.swing.JPanel panelDadosPedido;
    private javax.swing.JPanel panelIngredientes;
    private javax.swing.JPanel panelPedido;
    private javax.swing.JPanel panelSabores;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelTotalPedido;
    private javax.swing.JTextField txtAtendente;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCEP;
    private javax.swing.JTextArea txtCarrinho;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodProduto;
    private javax.swing.JTextField txtCompl;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtObsCliente;
    private javax.swing.JTextField txtObsPedido;
    private javax.swing.JTextField txtQtdProduto;
    private javax.swing.JTextField txtTotalPedido;
    private javax.swing.JTextField txtValorBorda;
    private javax.swing.JTextField txtValorProduto;
    // End of variables declaration//GEN-END:variables
}
