/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.dsystem.view;

import br.com.dsystem.controller.FuncionarioController;
import br.com.dsystem.model.Funcionario;
import br.com.dsystem.util.CamposNumericos;
import br.com.dsystem.util.Utilitários;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class FrmFuncionario extends javax.swing.JFrame {

    private final FuncionarioController funcController = new FuncionarioController();
    private boolean eNovo;
    private String cpfAntes;
    private String login;
    private String senha;
    private Funcionario pFunc;

    /**
     * Creates new form FrmLayoutCadastro
     */
    public FrmFuncionario() {
        initComponents();
        btnSalvar.setVisible(false);
        btnCancelar.setVisible(false);
        pFunc = new Funcionario();
        txtCodigo.setDocument(new CamposNumericos(4));
        txtNumero.setDocument(new CamposNumericos(4));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpDadosPrincipais = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblPessoa = new javax.swing.JLabel();
        jcbPessoa = new javax.swing.JComboBox<>();
        lblCpfCnpj = new javax.swing.JLabel();
        txtCpfCnpj = new javax.swing.JFormattedTextField();
        lblRG = new javax.swing.JLabel();
        txtRG = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        txtCelular = new javax.swing.JFormattedTextField();
        lblFixo = new javax.swing.JLabel();
        txtFixo = new javax.swing.JFormattedTextField();
        lblCEP = new javax.swing.JLabel();
        txtCEP = new javax.swing.JFormattedTextField();
        btnBuscaCEP = new javax.swing.JButton();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        lblCompl = new javax.swing.JLabel();
        txtCompl = new javax.swing.JTextField();
        jcbEstado = new javax.swing.JComboBox<>();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblObs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        btnPesquisaFuncionario = new javax.swing.JButton();
        btnBuscarCodigo = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        jcbCargo = new javax.swing.JComboBox<>();
        jcbPerfil = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jrbAtivo = new javax.swing.JRadioButton();
        btnSalvar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sys Vendas - Cadastro de Funcionários");
        setMinimumSize(new java.awt.Dimension(805, 560));
        setResizable(false);
        setSize(new java.awt.Dimension(805, 560));

        jPanel1.setBackground(new java.awt.Color(72, 128, 242));
        jPanel1.setPreferredSize(new java.awt.Dimension(914, 73));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cadastro de Funcionários");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(499, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jpDadosPrincipais.setBackground(new java.awt.Color(255, 255, 255));

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCodigo.setText("Código:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nome:");

        txtNome.setEditable(false);
        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblPessoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPessoa.setText("Pesosa:");

        jcbPessoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcbPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FÍSICA", "JURÍDICA" }));
        jcbPessoa.setEnabled(false);
        jcbPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPessoaActionPerformed(evt);
            }
        });

        lblCpfCnpj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCpfCnpj.setText("CPF/CNPJ:");

        txtCpfCnpj.setEditable(false);
        try {
            txtCpfCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfCnpj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblRG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRG.setText("RG/IE:");

        txtRG.setEditable(false);
        txtRG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblCelular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCelular.setText("Celuar:");

        txtCelular.setEditable(false);
        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblFixo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFixo.setText("Fixo:");

        txtFixo.setEditable(false);
        try {
            txtFixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFixo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblCEP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCEP.setText("CEP:");

        txtCEP.setEditable(false);
        try {
            txtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCEP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnBuscaCEP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscaCEP.setText("Buscar");
        btnBuscaCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaCEPActionPerformed(evt);
            }
        });
        btnBuscaCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBuscaCEPKeyPressed(evt);
            }
        });

        lblEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEndereco.setText("Endereço:");

        txtEndereco.setEditable(false);
        txtEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNumero.setText("Nº");

        lblCompl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCompl.setText("Compl:");

        txtCompl.setEditable(false);
        txtCompl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jcbEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jcbEstado.setEnabled(false);

        lblBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBairro.setText("Bairro: ");

        txtBairro.setEditable(false);
        txtBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCidade.setText("Cidade: ");

        txtCidade.setEditable(false);
        txtCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmail.setText("E-mail:");

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblObs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblObs.setText("OBS: ");

        txtObs.setEditable(false);
        txtObs.setColumns(20);
        txtObs.setRows(5);
        jScrollPane1.setViewportView(txtObs);

        btnPesquisaFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPesquisaFuncionario.setText("Pesquisar ");
        btnPesquisaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaFuncionarioActionPerformed(evt);
            }
        });
        btnPesquisaFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPesquisaFuncionarioKeyPressed(evt);
            }
        });

        btnBuscarCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscarCodigo.setText("Buscar");
        btnBuscarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCodigoActionPerformed(evt);
            }
        });
        btnBuscarCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBuscarCodigoKeyPressed(evt);
            }
        });

        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jcbCargo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atendente", "Supervisor", "Gerente", "Gestor" }));
        jcbCargo.setEnabled(false);

        jcbPerfil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcbPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADM", "USUÁRIO" }));
        jcbPerfil.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Cargo");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Perfil");

        jrbAtivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jrbAtivo.setText("Usuário Ativo");

        javax.swing.GroupLayout jpDadosPrincipaisLayout = new javax.swing.GroupLayout(jpDadosPrincipais);
        jpDadosPrincipais.setLayout(jpDadosPrincipaisLayout);
        jpDadosPrincipaisLayout.setHorizontalGroup(
            jpDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosPrincipaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosPrincipaisLayout.createSequentialGroup()
                        .addComponent(lblObs)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1))
                    .addGroup(jpDadosPrincipaisLayout.createSequentialGroup()
                        .addGroup(jpDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPessoa)
                            .addComponent(lblCEP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDadosPrincipaisLayout.createSequentialGroup()
                                .addGroup(jpDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpDadosPrincipaisLayout.createSequentialGroup()
                                        .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscaCEP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblEndereco)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDadosPrincipaisLayout.createSequentialGroup()
                                        .addComponent(txtCompl, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83)))
                                .addGroup(jpDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpDadosPrincipaisLayout.createSequentialGroup()
                                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblNumero))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDadosPrincipaisLayout.createSequentialGroup()
                                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCidade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumero))
                            .addGroup(jpDadosPrincipaisLayout.createSequentialGroup()
                                .addComponent(jcbPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCpfCnpj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblRG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jpDadosPrincipaisLayout.createSequentialGroup()
                        .addComponent(lblCompl)
                        .addGap(209, 209, 209)
                        .addComponent(lblBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDadosPrincipaisLayout.createSequentialGroup()
                        .addGroup(jpDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDadosPrincipaisLayout.createSequentialGroup()
                                .addComponent(lblCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarCodigo)
                                .addGap(122, 122, 122)
                                .addComponent(jrbAtivo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jpDadosPrincipaisLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addGap(12, 12, 12)
                        .addGroup(jpDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDadosPrincipaisLayout.createSequentialGroup()
                                .addComponent(btnPesquisaFuncionario)
                                .addGap(38, 38, 38))))
                    .addGroup(jpDadosPrincipaisLayout.createSequentialGroup()
                        .addGroup(jpDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addGroup(jpDadosPrincipaisLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(lblCelular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFixo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpDadosPrincipaisLayout.setVerticalGroup(
            jpDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosPrincipaisLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(btnPesquisaFuncionario)
                    .addComponent(btnBuscarCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbAtivo))
                .addGap(32, 32, 32)
                .addGroup(jpDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPessoa)
                    .addComponent(jcbPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpfCnpj)
                    .addComponent(txtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRG)
                    .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCEP)
                        .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscaCEP)
                        .addComponent(lblEndereco)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNumero))
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompl)
                    .addComponent(txtCompl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCidade)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCelular)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFixo)
                    .addComponent(txtFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObs)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados Principais", jpDadosPrincipais);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salvar.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.setPreferredSize(new java.awt.Dimension(35, 35));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/novo.png"))); // NOI18N
        btnNovo.setToolTipText("Novo");
        btnNovo.setPreferredSize(new java.awt.Dimension(35, 35));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        btnEditar.setToolTipText("Editar");
        btnEditar.setPreferredSize(new java.awt.Dimension(35, 35));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir.png"))); // NOI18N
        btnExcluir.setToolTipText("Excluir");
        btnExcluir.setPreferredSize(new java.awt.Dimension(35, 35));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voltar.png"))); // NOI18N
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.setPreferredSize(new java.awt.Dimension(35, 35));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(354, 354, 354)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        btnCancelar.getAccessibleContext().setAccessibleName("Cancelar");

        setBounds(0, 0, 873, 607);
    }// </editor-fold>//GEN-END:initComponents

    private void jcbPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPessoaActionPerformed
        if (jcbPessoa.getSelectedIndex() == 0) {
            txtCpfCnpj.setValue(null);
            try {
                txtCpfCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
            } catch (ParseException e) {

            }
        } else {
            txtCpfCnpj.setValue(null);
            try {
                txtCpfCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
            } catch (ParseException e) {

            }
        }
    }//GEN-LAST:event_jcbPessoaActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        limpaCampos();
        habilitaEdicao();
        eNovo = true;
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (txtCodigo.getText().isEmpty() || txtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione um funcionario para edição!");
        } else {
            cpfAntes = txtCpfCnpj.getText();
            pFunc = funcController.buscaIdFuncionario(txtCodigo.getText());
            txtCodigo.setText(Integer.toString(pFunc.getId()));
            jrbAtivo.setEnabled(false);
            habilitaEdicao();
            eNovo = false;
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (eNovo == true) {
            try {
                if (jrbAtivo.isSelected() == true) {
                    DlgDefinirAcesso defineSenha = new DlgDefinirAcesso(this, true);
                    defineSenha.setVisible(true);
                    login = defineSenha.getLogin();
                    senha = defineSenha.getSenha();
                }
                funcController.cadastrarFuncionario(txtNome.getText(), jcbPerfil.getSelectedItem().toString(), jcbPessoa.getSelectedItem().toString(), txtCpfCnpj.getText(),
                        txtRG.getText(), jcbCargo.getSelectedItem().toString(), txtCEP.getText(), txtEndereco.getText(), txtNumero.getText(),
                        txtCompl.getText(), txtBairro.getText(), txtCidade.getText(), jcbEstado.getSelectedItem().toString(), txtFixo.getText(),
                        txtCelular.getText(), txtEmail.getText(), txtObs.getText(), jrbAtivo.isSelected(), login, senha);

                JOptionPane.showMessageDialog(null, "Funcionário Cadastrado\nCom Sucesso!", "Funcionários", JOptionPane.INFORMATION_MESSAGE);
                limpaCampos();
                fechaEdicao();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Funcionarios", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            try {
                funcController.atualizarFuncionario(txtCodigo.getText(), txtNome.getText(), jcbPerfil.getSelectedItem().toString(), jcbPessoa.getSelectedItem().toString(), txtCpfCnpj.getText(),
                        txtRG.getText(), jcbCargo.getSelectedItem().toString(), txtCEP.getText(), txtEndereco.getText(), txtNumero.getText(),
                        txtCompl.getText(), txtBairro.getText(), txtCidade.getText(), jcbEstado.getSelectedItem().toString(), txtFixo.getText(),
                        txtCelular.getText(), txtEmail.getText(), txtObs.getText(), jrbAtivo.isSelected(), this.cpfAntes);

                JOptionPane.showMessageDialog(null, "Funcionário Atualizado\nCom Sucesso!", "Funcionários", JOptionPane.INFORMATION_MESSAGE);
                fechaEdicao();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Funcionarios", JOptionPane.WARNING_MESSAGE);
            }
        }


    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (txtCodigo.getText().isEmpty() || txtNome.getText().isEmpty()) {
            limpaCampos();
            fechaEdicao();
        } else {
            try {
                pFunc = funcController.buscaIdFuncionario(txtCodigo.getText());

                txtCodigo.setText(Integer.toString(pFunc.getId()));
                txtNome.setText(pFunc.getNome());
                jrbAtivo.setSelected(pFunc.getAtivo());
                jcbPerfil.setSelectedItem(pFunc.getNivel_acesso());
                jcbPessoa.setSelectedItem(pFunc.getPessoa());
                txtCpfCnpj.setText(pFunc.getCpf());
                txtRG.setText(pFunc.getRg());
                jcbCargo.setSelectedItem(pFunc.getCargo());
                txtCEP.setText(pFunc.getCep());
                txtEndereco.setText(pFunc.getEndereco());
                txtNumero.setText(Integer.toString(pFunc.getNumero()));
                txtCompl.setText(pFunc.getCompl());
                txtBairro.setText(pFunc.getBairro());
                txtCidade.setText(pFunc.getCidade());
                jcbEstado.setSelectedItem(pFunc.getEstado());
                txtCelular.setText(pFunc.getCelular());
                txtFixo.setText(pFunc.getFoneFixo());
                txtEmail.setText(pFunc.getEmail());
                txtObs.setText(pFunc.getObs());
                fechaEdicao();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Funcionarios", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (txtCodigo.getText().isEmpty() || txtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione um Funcionário para Excluir");
        } else {
            try {
                if (funcController.buscaFuncionario( txtCodigo.getText(),txtCpfCnpj.getText())) {
                    int resp = JOptionPane.showConfirmDialog(null, "Confirma Exclusão do Funcionário?", "Funcionarios", JOptionPane.YES_NO_OPTION);

                    if (resp == JOptionPane.YES_OPTION) {
                        funcController.deletarFuncionario(txtCodigo.getText());
                        JOptionPane.showMessageDialog(null, "Funcionário Excluído\nCom Sucesso!", "Funcionários", JOptionPane.INFORMATION_MESSAGE);
                        limpaCampos();
                        fechaEdicao();
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Funcionario não Cadastrado", "Funcionarios", JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Funcionarios", JOptionPane.WARNING_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnBuscaCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaCEPActionPerformed

        try {
            Funcionario func = funcController.buscaCEPFuncionario(txtCEP.getText());

            txtEndereco.setText(func.getEndereco());
            txtBairro.setText(func.getBairro());
            txtCidade.setText(func.getCidade());
            jcbEstado.setSelectedItem(func.getEstado());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Funcionarios", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnBuscaCEPActionPerformed

    private void btnPesquisaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaFuncionarioActionPerformed
        DlgGradeFuncionarios grade = new DlgGradeFuncionarios(this, true);
        grade.setVisible(true);
        String codigo = grade.getCodigo();

        Funcionario f = funcController.buscaIdFuncionario(codigo);
        txtCodigo.setText(Integer.toString(f.getId()));
        txtNome.setText(f.getNome());
        jrbAtivo.setSelected(f.getAtivo());
        jcbPerfil.setSelectedItem(f.getNivel_acesso());
        jcbPessoa.setSelectedItem(f.getPessoa());
        txtCpfCnpj.setText(f.getCpf());
        txtRG.setText(f.getRg());
        jcbCargo.setSelectedItem(f.getCargo());
        txtCEP.setText(f.getCep());
        txtEndereco.setText(f.getEndereco());
        txtNumero.setText(Integer.toString(f.getNumero()));
        txtCompl.setText(f.getCompl());
        txtBairro.setText(f.getBairro());
        txtCidade.setText(f.getCidade());
        jcbEstado.setSelectedItem(f.getEstado());
        txtCelular.setText(f.getCelular());
        txtFixo.setText(f.getFoneFixo());
        txtEmail.setText(f.getEmail());
        txtObs.setText(f.getObs());
    }//GEN-LAST:event_btnPesquisaFuncionarioActionPerformed

    private void btnBuscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCodigoActionPerformed
        if (txtCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione um funcionario para pesquisar!");
        } else {
            try {
                Funcionario f = funcController.buscaIdFuncionario(txtCodigo.getText());
                txtCodigo.setText(Integer.toString(f.getId()));
                txtNome.setText(f.getNome());
                jrbAtivo.setSelected(f.getAtivo());
                jcbPerfil.setSelectedItem(f.getNivel_acesso());
                jcbPessoa.setSelectedItem(f.getPessoa());
                txtCpfCnpj.setText(f.getCpf());
                txtRG.setText(f.getRg());
                jcbCargo.setSelectedItem(f.getCargo());
                txtCEP.setText(f.getCep());
                txtEndereco.setText(f.getEndereco());
                txtNumero.setText(Integer.toString(f.getNumero()));
                txtCompl.setText(f.getCompl());
                txtBairro.setText(f.getBairro());
                txtCidade.setText(f.getCidade());
                jcbEstado.setSelectedItem(f.getEstado());
                txtCelular.setText(f.getCelular());
                txtFixo.setText(f.getFoneFixo());
                txtEmail.setText(f.getEmail());
                txtObs.setText(f.getObs());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Funcionarios", JOptionPane.WARNING_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnBuscarCodigoActionPerformed

    private void btnBuscarCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscarCodigoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtCodigo.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Selecione um funcionario para pesquisar!");
            } else {
                Funcionario f = funcController.buscaIdFuncionario(txtCodigo.getText());
                txtCodigo.setText(Integer.toString(f.getId()));
                txtNome.setText(f.getNome());
                jrbAtivo.setSelected(f.getAtivo());
                jcbPerfil.setSelectedItem(f.getNivel_acesso());
                jcbPessoa.setSelectedItem(f.getPessoa());
                txtCpfCnpj.setText(f.getCpf());
                txtRG.setText(f.getRg());
                jcbCargo.setSelectedItem(f.getCargo());
                txtCEP.setText(f.getCep());
                txtEndereco.setText(f.getEndereco());
                txtNumero.setText(Integer.toString(f.getNumero()));
                txtCompl.setText(f.getCompl());
                txtBairro.setText(f.getBairro());
                txtCidade.setText(f.getCidade());
                jcbEstado.setSelectedItem(f.getEstado());
                txtCelular.setText(f.getCelular());
                txtFixo.setText(f.getFoneFixo());
                txtEmail.setText(f.getEmail());
                txtObs.setText(f.getObs());

            }
        }
    }//GEN-LAST:event_btnBuscarCodigoKeyPressed

    private void btnBuscaCEPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscaCEPKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                Funcionario func = funcController.buscaCEPFuncionario(txtCEP.getText());

                txtEndereco.setText(func.getEndereco());
                txtBairro.setText(func.getBairro());
                txtCidade.setText(func.getCidade());
                jcbEstado.setSelectedItem(func.getEstado());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Funcionarios", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnBuscaCEPKeyPressed

    private void btnPesquisaFuncionarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPesquisaFuncionarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DlgGradeFuncionarios grade = new DlgGradeFuncionarios(this, true);
            grade.setVisible(true);
            String codigo = grade.getCodigo();

            Funcionario f = funcController.buscaIdFuncionario(codigo);
            txtCodigo.setText(Integer.toString(f.getId()));
            txtNome.setText(f.getNome());
            jrbAtivo.setSelected(f.getAtivo());
            jcbPerfil.setSelectedItem(f.getNivel_acesso());
            jcbPessoa.setSelectedItem(f.getPessoa());
            txtCpfCnpj.setText(f.getCpf());
            txtRG.setText(f.getRg());
            jcbCargo.setSelectedItem(f.getCargo());
            txtCEP.setText(f.getCep());
            txtEndereco.setText(f.getEndereco());
            txtNumero.setText(Integer.toString(f.getNumero()));
            txtCompl.setText(f.getCompl());
            txtBairro.setText(f.getBairro());
            txtCidade.setText(f.getCidade());
            jcbEstado.setSelectedItem(f.getEstado());
            txtCelular.setText(f.getCelular());
            txtFixo.setText(f.getFoneFixo());
            txtEmail.setText(f.getEmail());
            txtObs.setText(f.getObs());
        }
    }//GEN-LAST:event_btnPesquisaFuncionarioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaCEP;
    private javax.swing.JButton btnBuscarCodigo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisaFuncionario;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcbCargo;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JComboBox<String> jcbPerfil;
    private javax.swing.JComboBox<String> jcbPessoa;
    private javax.swing.JPanel jpDadosPrincipais;
    private javax.swing.JRadioButton jrbAtivo;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCompl;
    private javax.swing.JLabel lblCpfCnpj;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblFixo;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblObs;
    private javax.swing.JLabel lblPessoa;
    private javax.swing.JLabel lblRG;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCEP;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCompl;
    private javax.swing.JFormattedTextField txtCpfCnpj;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JFormattedTextField txtFixo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextArea txtObs;
    private javax.swing.JTextField txtRG;
    // End of variables declaration//GEN-END:variables

    //MÉTODOS
    private void limpaCampos() {
        new Utilitários().limparTela(jpDadosPrincipais);
        txtObs.setText("");
    }

    private void habilitaEdicao() {
        txtCodigo.setEditable(false);
        txtNome.setEditable(true);
        txtCelular.setEditable(true);
        txtFixo.setEditable(true);
        jcbPessoa.setEnabled(true);
        txtCpfCnpj.setEditable(true);
        txtRG.setEditable(true);
        txtCEP.setEditable(true);
        txtEndereco.setEditable(true);
        txtNumero.setEditable(true);
        txtCompl.setEditable(true);
        txtBairro.setEditable(true);
        txtCidade.setEditable(true);
        jcbEstado.setEnabled(true);
        txtEmail.setEditable(true);
        txtObs.setEditable(true);
        jcbPerfil.setEnabled(true);
        jcbCargo.setEnabled(true);
        btnNovo.setVisible(false);
        btnSalvar.setVisible(true);
        btnEditar.setVisible(false);
        btnExcluir.setVisible(false);
        btnCancelar.setVisible(true);
    }

    private void fechaEdicao() {
        txtCodigo.setEditable(true);
        txtNome.setEditable(false);
        txtCelular.setEditable(false);
        txtFixo.setEditable(false);
        jcbPessoa.setEnabled(false);
        txtCpfCnpj.setEditable(false);
        txtRG.setEditable(false);
        txtCEP.setEditable(false);
        txtEndereco.setEditable(false);
        txtNumero.setEditable(false);
        txtCompl.setEditable(false);
        txtBairro.setEditable(false);
        txtCidade.setEditable(false);
        jcbEstado.setEnabled(false);
        txtEmail.setEditable(false);
        txtObs.setEditable(false);
        jcbPerfil.setEnabled(true);
        jcbCargo.setEnabled(true);
        btnNovo.setVisible(true);
        btnSalvar.setVisible(false);
        btnEditar.setVisible(true);
        btnExcluir.setVisible(true);
        btnCancelar.setVisible(false);
    }

}
