/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.dsystem.view;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author david
 */
public class ZFrmPrincipal123 extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal123
     */
    boolean a = true;
    public ZFrmPrincipal123() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpHeader = new javax.swing.JPanel();
        jpMenu = new javax.swing.JPanel();
        jpMenuIcones = new javax.swing.JPanel();
        jpLinhaConfig = new javax.swing.JPanel();
        jpConfig = new javax.swing.JPanel();
        jblBotaoConfig = new javax.swing.JLabel();
        jpEsconeMenu = new javax.swing.JPanel();
        lblBotaoMenu = new javax.swing.JLabel();
        jpLinhaEscondeMenu = new javax.swing.JPanel();
        jpMenuEsconder = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jpDashBoard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpHeader.setBackground(new java.awt.Color(15, 19, 42));
        jpHeader.setPreferredSize(new java.awt.Dimension(800, 50));
        jpHeader.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jpHeader, java.awt.BorderLayout.PAGE_START);

        jpMenu.setPreferredSize(new java.awt.Dimension(270, 450));
        jpMenu.setLayout(new java.awt.BorderLayout());

        jpMenuIcones.setBackground(new java.awt.Color(15, 19, 42));
        jpMenuIcones.setPreferredSize(new java.awt.Dimension(50, 450));
        jpMenuIcones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpLinhaConfig.setBackground(new java.awt.Color(5, 10, 46));
        jpLinhaConfig.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout jpLinhaConfigLayout = new javax.swing.GroupLayout(jpLinhaConfig);
        jpLinhaConfig.setLayout(jpLinhaConfigLayout);
        jpLinhaConfigLayout.setHorizontalGroup(
            jpLinhaConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jpLinhaConfigLayout.setVerticalGroup(
            jpLinhaConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jpMenuIcones.add(jpLinhaConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 50, 5));

        jpConfig.setBackground(new java.awt.Color(5, 10, 46));
        jpConfig.setLayout(new java.awt.BorderLayout());

        jblBotaoConfig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblBotaoConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings_32px.png"))); // NOI18N
        jblBotaoConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblBotaoConfigMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblBotaoConfigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblBotaoConfigMouseExited(evt);
            }
        });
        jpConfig.add(jblBotaoConfig, java.awt.BorderLayout.CENTER);

        jpMenuIcones.add(jpConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 50, 50));

        jpEsconeMenu.setBackground(new java.awt.Color(5, 10, 46));
        jpEsconeMenu.setLayout(new java.awt.BorderLayout());

        lblBotaoMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBotaoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_32px.png"))); // NOI18N
        lblBotaoMenu.setToolTipText("");
        lblBotaoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBotaoMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBotaoMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBotaoMenuMouseExited(evt);
            }
        });
        jpEsconeMenu.add(lblBotaoMenu, java.awt.BorderLayout.CENTER);

        jpMenuIcones.add(jpEsconeMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 50, 50));

        jpLinhaEscondeMenu.setBackground(new java.awt.Color(5, 10, 46));
        jpLinhaEscondeMenu.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout jpLinhaEscondeMenuLayout = new javax.swing.GroupLayout(jpLinhaEscondeMenu);
        jpLinhaEscondeMenu.setLayout(jpLinhaEscondeMenuLayout);
        jpLinhaEscondeMenuLayout.setHorizontalGroup(
            jpLinhaEscondeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jpLinhaEscondeMenuLayout.setVerticalGroup(
            jpLinhaEscondeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jpMenuIcones.add(jpLinhaEscondeMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 5));

        jpMenu.add(jpMenuIcones, java.awt.BorderLayout.LINE_START);

        jpMenuEsconder.setBackground(new java.awt.Color(25, 29, 74));

        lblLogo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo.setText("LogoTipo");

        javax.swing.GroupLayout jpMenuEsconderLayout = new javax.swing.GroupLayout(jpMenuEsconder);
        jpMenuEsconder.setLayout(jpMenuEsconderLayout);
        jpMenuEsconderLayout.setHorizontalGroup(
            jpMenuEsconderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuEsconderLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jpMenuEsconderLayout.setVerticalGroup(
            jpMenuEsconderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuEsconderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(499, Short.MAX_VALUE))
        );

        jpMenu.add(jpMenuEsconder, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpMenu, java.awt.BorderLayout.LINE_START);

        jpDashBoard.setBackground(new java.awt.Color(72, 128, 242));

        javax.swing.GroupLayout jpDashBoardLayout = new javax.swing.GroupLayout(jpDashBoard);
        jpDashBoard.setLayout(jpDashBoardLayout);
        jpDashBoardLayout.setHorizontalGroup(
            jpDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jpDashBoardLayout.setVerticalGroup(
            jpDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );

        getContentPane().add(jpDashBoard, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* 
    *Método que muda a cor da linha acima do menu no painel lateral, inicadno a seleção da opção 
    */
    public void trocaCor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    /**
    *  Método que altera a cor do botão ao clicar 
     * @param h1
     * @param h2
     * @param numberbool
    */
    public void clicaMenu( JPanel h1, JPanel h2, int numberbool){
        if(numberbool == 1){
            h1.setBackground(new Color(25,29,74));
            h2.setBackground(new Color(5,10,46));
        }else{
            h1.setBackground(new Color(5,10,46));
            h2.setBackground(new Color(25,29,74));
        }
        
    }
    
    /**
    *  Método que altera a imagem do menu lateral
     * @param botao 
     * @param resourceImg
    */
    
    public void mudaImagem(JLabel botao,String resourceImg ){
        ImageIcon aimg = new ImageIcon(getClass().getResource(resourceImg));
        botao.setIcon(aimg);
    }
    
    /**
     *  Método que oculta e mostrar o menu do painel
     * @param menushow
     * @param dashboard
     * @param botao
     */
    public void mostraEsconde(JPanel menushow, boolean dashboard, JLabel botao){
    if(dashboard == true){
        menushow.setPreferredSize(new Dimension(50, menushow.getHeight()));
        mudaImagem(botao, "/images/menu_32px.png");
    }else{
        menushow.setPreferredSize(new Dimension(270, menushow.getHeight()));
        mudaImagem(botao, "/images/back_32px.png");
    }
        
    }
    
    private void lblBotaoMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoMenuMouseEntered
        trocaCor(jpLinhaEscondeMenu, new Color (247,78,105));
    }//GEN-LAST:event_lblBotaoMenuMouseEntered

    private void lblBotaoMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoMenuMouseExited
        trocaCor(jpLinhaEscondeMenu, new Color (5,10,46));
    }//GEN-LAST:event_lblBotaoMenuMouseExited

    private void lblBotaoMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotaoMenuMouseClicked
        clicaMenu(jpEsconeMenu, jpConfig, 1);
        // criar vazio para o método ocultar e mostrar o menu do painel
        if(a==true){
            mostraEsconde(jpMenu, a, lblBotaoMenu);
            SwingUtilities.updateComponentTreeUI(this);
            //Criar método que muda a imagem do menu
            a=false;
        }else{
            mostraEsconde(jpMenu, a, lblBotaoMenu);
            SwingUtilities.updateComponentTreeUI(this);
            a=true;
        }
        
        
    }//GEN-LAST:event_lblBotaoMenuMouseClicked

    private void jblBotaoConfigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblBotaoConfigMouseEntered
        trocaCor(jpLinhaConfig, new Color(8,177,150));
    }//GEN-LAST:event_jblBotaoConfigMouseEntered

    private void jblBotaoConfigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblBotaoConfigMouseExited
       trocaCor(jpLinhaConfig, new Color(5,10,46));
    }//GEN-LAST:event_jblBotaoConfigMouseExited

    private void jblBotaoConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblBotaoConfigMouseClicked
         clicaMenu( jpConfig, jpEsconeMenu, 1);
    }//GEN-LAST:event_jblBotaoConfigMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZFrmPrincipal123.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZFrmPrincipal123.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZFrmPrincipal123.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZFrmPrincipal123.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZFrmPrincipal123().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jblBotaoConfig;
    private javax.swing.JPanel jpConfig;
    private javax.swing.JPanel jpDashBoard;
    private javax.swing.JPanel jpEsconeMenu;
    private javax.swing.JPanel jpHeader;
    private javax.swing.JPanel jpLinhaConfig;
    private javax.swing.JPanel jpLinhaEscondeMenu;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpMenuEsconder;
    private javax.swing.JPanel jpMenuIcones;
    private javax.swing.JLabel lblBotaoMenu;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
